version: '3'

services:

    # Nginx service
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www/
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            - "8080:80"
        depends_on:
            - app
        container_name: blog_laravel_nginx

    # PHP service
    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www/
        depends_on:
            - db
        container_name: blog_laravel_app

    # MySQL service
    db:
        image: mysql:5.7
        restart: always
        volumes:
            - ./tmp/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: blog_laravel
            MYSQL_ROOT_PASSWORD: root # for root user
        ports:
            - "8081:3306"
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: blog_laravel_db

    # PhpMyAdmin service
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - "8082:80"
        environment:
            MYSQL_ROOT_PASSWORD: root # password for the root superuser account
            PMA_HOST: db # address/hostname of the mysql server = mysql container name
            PMA_USER: root # login on startup
            PMA_PASSWORD: root # login on startup
        depends_on:
            - db
        container_name: blog_laravel_phpmyadmin
